name: e_alerto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+4
  font_awesome_flutter: ^10.8.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  http: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  geocoding: ^3.0.0
  geolocator: ^10.1.0
  geolocator_android: ^4.1.7
  permission_handler: ^11.0.1
  intl: ^0.19.0
  flutter_otp_text_field: ^1.5.1+1
  pinput: ^5.0.1
  flutter_image_compress: ^2.4.0
  timeago: ^3.2.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
    - assets/images/
    - assets/images/image3.png
    - assets/images/logos/E-ALERTO_Logo_Colored.png
    - assets/images/icons/google_icon.png
    - assets/images/section_boxes_images/
    - backend/.env