// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8WkxOuqI8USg4WtO_Kj-tRwR1doHnnlw',
    appId: '1:288160619445:web:47473fcbbbf692c97757fc',
    messagingSenderId: '288160619445',
    projectId: 'e-alerto-34adf',
    authDomain: 'e-alerto-34adf.firebaseapp.com',
    storageBucket: 'e-alerto-34adf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtwljZKzdxkXX6bk2zX-1BJyYfPUerjAU',
    appId: '1:288160619445:android:c612f7691e446c1e7757fc',
    messagingSenderId: '288160619445',
    projectId: 'e-alerto-34adf',
    storageBucket: 'e-alerto-34adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA29pvT-Rfolw20vhM-hYe0qKiyplMjUyY',
    appId: '1:288160619445:ios:6f0d6214d6cfbec17757fc',
    messagingSenderId: '288160619445',
    projectId: 'e-alerto-34adf',
    storageBucket: 'e-alerto-34adf.firebasestorage.app',
    androidClientId: '288160619445-qtkmrdjpv67n8gf5ric0kl4it3iqtg44.apps.googleusercontent.com',
    iosClientId: '288160619445-vvncm8p98ofccqvd9mghi0po6fd2g0sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eAlerto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA29pvT-Rfolw20vhM-hYe0qKiyplMjUyY',
    appId: '1:288160619445:ios:6f0d6214d6cfbec17757fc',
    messagingSenderId: '288160619445',
    projectId: 'e-alerto-34adf',
    storageBucket: 'e-alerto-34adf.firebasestorage.app',
    androidClientId: '288160619445-qtkmrdjpv67n8gf5ric0kl4it3iqtg44.apps.googleusercontent.com',
    iosClientId: '288160619445-vvncm8p98ofccqvd9mghi0po6fd2g0sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eAlerto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8WkxOuqI8USg4WtO_Kj-tRwR1doHnnlw',
    appId: '1:288160619445:web:be683c26edaf45057757fc',
    messagingSenderId: '288160619445',
    projectId: 'e-alerto-34adf',
    authDomain: 'e-alerto-34adf.firebaseapp.com',
    storageBucket: 'e-alerto-34adf.firebasestorage.app',
  );

}